/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsRouteRouteImport } from './routes/shops/route'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopsIndexRouteImport } from './routes/shops/index'
import { Route as ShopsShopIdRouteRouteImport } from './routes/shops/$shopId/route'
import { Route as ShopsInvitesRouteImport } from './routes/shops/invites'
import { Route as ShopsShopIdIndexRouteImport } from './routes/shops/$shopId/index'
import { Route as ShopsShopIdInvitesRouteImport } from './routes/shops/$shopId/invites'
import { Route as ShopsShopIdManagersRouteImport } from './routes/shops/$shopId/managers'
import { Route as ShopsShopIdRolesRouteImport } from './routes/shops/$shopId/roles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRouteRoute = ShopsRouteRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopsRouteRoute,
} as any)
const ShopsShopIdRouteRoute = ShopsShopIdRouteRouteImport.update({
  id: '/$shopId',
  path: '/$shopId',
  getParentRoute: () => ShopsRouteRoute,
} as any)
const ShopsInvitesRoute = ShopsInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => ShopsRouteRoute,
} as any)
const ShopsShopIdIndexRoute = ShopsShopIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopsShopIdRouteRoute,
} as any)
const ShopsShopIdInvitesRoute = ShopsShopIdInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => ShopsShopIdRouteRoute,
} as any)
const ShopsShopIdManagersRoute = ShopsShopIdManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => ShopsShopIdRouteRoute,
} as any)
const ShopsShopIdRolesRoute = ShopsShopIdRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ShopsShopIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shops': typeof ShopsRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/shops/$shopId': typeof ShopsShopIdRouteRouteWithChildren
  '/shops/invites': typeof ShopsInvitesRoute
  '/shops/': typeof ShopsIndexRoute
  '/shops/$shopId/invites': typeof ShopsShopIdInvitesRoute
  '/shops/$shopId/managers': typeof ShopsShopIdManagersRoute
  '/shops/$shopId/roles': typeof ShopsShopIdRolesRoute
  '/shops/$shopId/': typeof ShopsShopIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/shops/invites': typeof ShopsInvitesRoute
  '/shops': typeof ShopsIndexRoute
  '/shops/$shopId/invites': typeof ShopsShopIdInvitesRoute
  '/shops/$shopId/managers': typeof ShopsShopIdManagersRoute
  '/shops/$shopId/roles': typeof ShopsShopIdRolesRoute
  '/shops/$shopId': typeof ShopsShopIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shops': typeof ShopsRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/shops/$shopId': typeof ShopsShopIdRouteRouteWithChildren
  '/shops/invites': typeof ShopsInvitesRoute
  '/shops/': typeof ShopsIndexRoute
  '/shops/$shopId/invites': typeof ShopsShopIdInvitesRoute
  '/shops/$shopId/managers': typeof ShopsShopIdManagersRoute
  '/shops/$shopId/roles': typeof ShopsShopIdRolesRoute
  '/shops/$shopId/': typeof ShopsShopIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shops'
    | '/signin'
    | '/signup'
    | '/shops/$shopId'
    | '/shops/invites'
    | '/shops/'
    | '/shops/$shopId/invites'
    | '/shops/$shopId/managers'
    | '/shops/$shopId/roles'
    | '/shops/$shopId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/shops/invites'
    | '/shops'
    | '/shops/$shopId/invites'
    | '/shops/$shopId/managers'
    | '/shops/$shopId/roles'
    | '/shops/$shopId'
  id:
    | '__root__'
    | '/'
    | '/shops'
    | '/signin'
    | '/signup'
    | '/shops/$shopId'
    | '/shops/invites'
    | '/shops/'
    | '/shops/$shopId/invites'
    | '/shops/$shopId/managers'
    | '/shops/$shopId/roles'
    | '/shops/$shopId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopsRouteRoute: typeof ShopsRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof ShopsRouteRoute
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteRouteImport
      parentRoute: typeof ShopsRouteRoute
    }
    '/shops/invites': {
      id: '/shops/invites'
      path: '/invites'
      fullPath: '/shops/invites'
      preLoaderRoute: typeof ShopsInvitesRouteImport
      parentRoute: typeof ShopsRouteRoute
    }
    '/shops/$shopId/': {
      id: '/shops/$shopId/'
      path: '/'
      fullPath: '/shops/$shopId/'
      preLoaderRoute: typeof ShopsShopIdIndexRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
    '/shops/$shopId/invites': {
      id: '/shops/$shopId/invites'
      path: '/invites'
      fullPath: '/shops/$shopId/invites'
      preLoaderRoute: typeof ShopsShopIdInvitesRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
    '/shops/$shopId/managers': {
      id: '/shops/$shopId/managers'
      path: '/managers'
      fullPath: '/shops/$shopId/managers'
      preLoaderRoute: typeof ShopsShopIdManagersRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
    '/shops/$shopId/roles': {
      id: '/shops/$shopId/roles'
      path: '/roles'
      fullPath: '/shops/$shopId/roles'
      preLoaderRoute: typeof ShopsShopIdRolesRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
  }
}

interface ShopsShopIdRouteRouteChildren {
  ShopsShopIdInvitesRoute: typeof ShopsShopIdInvitesRoute
  ShopsShopIdManagersRoute: typeof ShopsShopIdManagersRoute
  ShopsShopIdRolesRoute: typeof ShopsShopIdRolesRoute
  ShopsShopIdIndexRoute: typeof ShopsShopIdIndexRoute
}

const ShopsShopIdRouteRouteChildren: ShopsShopIdRouteRouteChildren = {
  ShopsShopIdInvitesRoute: ShopsShopIdInvitesRoute,
  ShopsShopIdManagersRoute: ShopsShopIdManagersRoute,
  ShopsShopIdRolesRoute: ShopsShopIdRolesRoute,
  ShopsShopIdIndexRoute: ShopsShopIdIndexRoute,
}

const ShopsShopIdRouteRouteWithChildren =
  ShopsShopIdRouteRoute._addFileChildren(ShopsShopIdRouteRouteChildren)

interface ShopsRouteRouteChildren {
  ShopsShopIdRouteRoute: typeof ShopsShopIdRouteRouteWithChildren
  ShopsInvitesRoute: typeof ShopsInvitesRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
}

const ShopsRouteRouteChildren: ShopsRouteRouteChildren = {
  ShopsShopIdRouteRoute: ShopsShopIdRouteRouteWithChildren,
  ShopsInvitesRoute: ShopsInvitesRoute,
  ShopsIndexRoute: ShopsIndexRoute,
}

const ShopsRouteRouteWithChildren = ShopsRouteRoute._addFileChildren(
  ShopsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopsRouteRoute: ShopsRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
