/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsRouteRouteImport } from './routes/shops/route'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopsIndexRouteImport } from './routes/shops/index'
import { Route as ShopsShopIdRouteRouteImport } from './routes/shops/$shopId/route'
import { Route as ShopsInvitesRouteImport } from './routes/shops/invites'
import { Route as ShopsShopIdIndexRouteImport } from './routes/shops/$shopId/index'
import { Route as ShopsShopIdAttributesRouteImport } from './routes/shops/$shopId/attributes'
import { Route as ShopsShopIdInvitesRouteImport } from './routes/shops/$shopId/invites'
import { Route as ShopsShopIdManagersRouteImport } from './routes/shops/$shopId/managers'
import { Route as ShopsShopIdProductsRouteRouteImport } from './routes/shops/$shopId/products/route'
import { Route as ShopsShopIdRolesRouteImport } from './routes/shops/$shopId/roles'
import { Route as ShopsShopIdVariantsRouteImport } from './routes/shops/$shopId/variants'
import { Route as ShopsShopIdProductsIndexRouteImport } from './routes/shops/$shopId/products/index'
import { Route as ShopsShopIdProductsProductIdRouteImport } from './routes/shops/$shopId/products/$productId'
import { Route as ShopsShopIdProductsNewRouteImport } from './routes/shops/$shopId/products/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRouteRoute = ShopsRouteRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopsRouteRoute,
} as any)
const ShopsShopIdRouteRoute = ShopsShopIdRouteRouteImport.update({
  id: '/$shopId',
  path: '/$shopId',
  getParentRoute: () => ShopsRouteRoute,
} as any)
const ShopsInvitesRoute = ShopsInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => ShopsRouteRoute,
} as any)
const ShopsShopIdIndexRoute = ShopsShopIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopsShopIdRouteRoute,
} as any)
const ShopsShopIdAttributesRoute = ShopsShopIdAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => ShopsShopIdRouteRoute,
} as any)
const ShopsShopIdInvitesRoute = ShopsShopIdInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => ShopsShopIdRouteRoute,
} as any)
const ShopsShopIdManagersRoute = ShopsShopIdManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => ShopsShopIdRouteRoute,
} as any)
const ShopsShopIdProductsRouteRoute =
  ShopsShopIdProductsRouteRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => ShopsShopIdRouteRoute,
  } as any)
const ShopsShopIdRolesRoute = ShopsShopIdRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ShopsShopIdRouteRoute,
} as any)
const ShopsShopIdVariantsRoute = ShopsShopIdVariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => ShopsShopIdRouteRoute,
} as any)
const ShopsShopIdProductsIndexRoute =
  ShopsShopIdProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShopsShopIdProductsRouteRoute,
  } as any)
const ShopsShopIdProductsProductIdRoute =
  ShopsShopIdProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => ShopsShopIdProductsRouteRoute,
  } as any)
const ShopsShopIdProductsNewRoute = ShopsShopIdProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShopsShopIdProductsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shops': typeof ShopsRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/shops/$shopId': typeof ShopsShopIdRouteRouteWithChildren
  '/shops/invites': typeof ShopsInvitesRoute
  '/shops/': typeof ShopsIndexRoute
  '/shops/$shopId/products': typeof ShopsShopIdProductsRouteRouteWithChildren
  '/shops/$shopId/attributes': typeof ShopsShopIdAttributesRoute
  '/shops/$shopId/invites': typeof ShopsShopIdInvitesRoute
  '/shops/$shopId/managers': typeof ShopsShopIdManagersRoute
  '/shops/$shopId/roles': typeof ShopsShopIdRolesRoute
  '/shops/$shopId/variants': typeof ShopsShopIdVariantsRoute
  '/shops/$shopId/': typeof ShopsShopIdIndexRoute
  '/shops/$shopId/products/$productId': typeof ShopsShopIdProductsProductIdRoute
  '/shops/$shopId/products/new': typeof ShopsShopIdProductsNewRoute
  '/shops/$shopId/products/': typeof ShopsShopIdProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/shops/invites': typeof ShopsInvitesRoute
  '/shops': typeof ShopsIndexRoute
  '/shops/$shopId/attributes': typeof ShopsShopIdAttributesRoute
  '/shops/$shopId/invites': typeof ShopsShopIdInvitesRoute
  '/shops/$shopId/managers': typeof ShopsShopIdManagersRoute
  '/shops/$shopId/roles': typeof ShopsShopIdRolesRoute
  '/shops/$shopId/variants': typeof ShopsShopIdVariantsRoute
  '/shops/$shopId': typeof ShopsShopIdIndexRoute
  '/shops/$shopId/products/$productId': typeof ShopsShopIdProductsProductIdRoute
  '/shops/$shopId/products/new': typeof ShopsShopIdProductsNewRoute
  '/shops/$shopId/products': typeof ShopsShopIdProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shops': typeof ShopsRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/shops/$shopId': typeof ShopsShopIdRouteRouteWithChildren
  '/shops/invites': typeof ShopsInvitesRoute
  '/shops/': typeof ShopsIndexRoute
  '/shops/$shopId/products': typeof ShopsShopIdProductsRouteRouteWithChildren
  '/shops/$shopId/attributes': typeof ShopsShopIdAttributesRoute
  '/shops/$shopId/invites': typeof ShopsShopIdInvitesRoute
  '/shops/$shopId/managers': typeof ShopsShopIdManagersRoute
  '/shops/$shopId/roles': typeof ShopsShopIdRolesRoute
  '/shops/$shopId/variants': typeof ShopsShopIdVariantsRoute
  '/shops/$shopId/': typeof ShopsShopIdIndexRoute
  '/shops/$shopId/products/$productId': typeof ShopsShopIdProductsProductIdRoute
  '/shops/$shopId/products/new': typeof ShopsShopIdProductsNewRoute
  '/shops/$shopId/products/': typeof ShopsShopIdProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shops'
    | '/signin'
    | '/signup'
    | '/shops/$shopId'
    | '/shops/invites'
    | '/shops/'
    | '/shops/$shopId/products'
    | '/shops/$shopId/attributes'
    | '/shops/$shopId/invites'
    | '/shops/$shopId/managers'
    | '/shops/$shopId/roles'
    | '/shops/$shopId/variants'
    | '/shops/$shopId/'
    | '/shops/$shopId/products/$productId'
    | '/shops/$shopId/products/new'
    | '/shops/$shopId/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/shops/invites'
    | '/shops'
    | '/shops/$shopId/attributes'
    | '/shops/$shopId/invites'
    | '/shops/$shopId/managers'
    | '/shops/$shopId/roles'
    | '/shops/$shopId/variants'
    | '/shops/$shopId'
    | '/shops/$shopId/products/$productId'
    | '/shops/$shopId/products/new'
    | '/shops/$shopId/products'
  id:
    | '__root__'
    | '/'
    | '/shops'
    | '/signin'
    | '/signup'
    | '/shops/$shopId'
    | '/shops/invites'
    | '/shops/'
    | '/shops/$shopId/products'
    | '/shops/$shopId/attributes'
    | '/shops/$shopId/invites'
    | '/shops/$shopId/managers'
    | '/shops/$shopId/roles'
    | '/shops/$shopId/variants'
    | '/shops/$shopId/'
    | '/shops/$shopId/products/$productId'
    | '/shops/$shopId/products/new'
    | '/shops/$shopId/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopsRouteRoute: typeof ShopsRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof ShopsRouteRoute
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteRouteImport
      parentRoute: typeof ShopsRouteRoute
    }
    '/shops/invites': {
      id: '/shops/invites'
      path: '/invites'
      fullPath: '/shops/invites'
      preLoaderRoute: typeof ShopsInvitesRouteImport
      parentRoute: typeof ShopsRouteRoute
    }
    '/shops/$shopId/': {
      id: '/shops/$shopId/'
      path: '/'
      fullPath: '/shops/$shopId/'
      preLoaderRoute: typeof ShopsShopIdIndexRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
    '/shops/$shopId/attributes': {
      id: '/shops/$shopId/attributes'
      path: '/attributes'
      fullPath: '/shops/$shopId/attributes'
      preLoaderRoute: typeof ShopsShopIdAttributesRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
    '/shops/$shopId/invites': {
      id: '/shops/$shopId/invites'
      path: '/invites'
      fullPath: '/shops/$shopId/invites'
      preLoaderRoute: typeof ShopsShopIdInvitesRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
    '/shops/$shopId/managers': {
      id: '/shops/$shopId/managers'
      path: '/managers'
      fullPath: '/shops/$shopId/managers'
      preLoaderRoute: typeof ShopsShopIdManagersRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
    '/shops/$shopId/products': {
      id: '/shops/$shopId/products'
      path: '/products'
      fullPath: '/shops/$shopId/products'
      preLoaderRoute: typeof ShopsShopIdProductsRouteRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
    '/shops/$shopId/roles': {
      id: '/shops/$shopId/roles'
      path: '/roles'
      fullPath: '/shops/$shopId/roles'
      preLoaderRoute: typeof ShopsShopIdRolesRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
    '/shops/$shopId/variants': {
      id: '/shops/$shopId/variants'
      path: '/variants'
      fullPath: '/shops/$shopId/variants'
      preLoaderRoute: typeof ShopsShopIdVariantsRouteImport
      parentRoute: typeof ShopsShopIdRouteRoute
    }
    '/shops/$shopId/products/': {
      id: '/shops/$shopId/products/'
      path: '/'
      fullPath: '/shops/$shopId/products/'
      preLoaderRoute: typeof ShopsShopIdProductsIndexRouteImport
      parentRoute: typeof ShopsShopIdProductsRouteRoute
    }
    '/shops/$shopId/products/$productId': {
      id: '/shops/$shopId/products/$productId'
      path: '/$productId'
      fullPath: '/shops/$shopId/products/$productId'
      preLoaderRoute: typeof ShopsShopIdProductsProductIdRouteImport
      parentRoute: typeof ShopsShopIdProductsRouteRoute
    }
    '/shops/$shopId/products/new': {
      id: '/shops/$shopId/products/new'
      path: '/new'
      fullPath: '/shops/$shopId/products/new'
      preLoaderRoute: typeof ShopsShopIdProductsNewRouteImport
      parentRoute: typeof ShopsShopIdProductsRouteRoute
    }
  }
}

interface ShopsShopIdProductsRouteRouteChildren {
  ShopsShopIdProductsProductIdRoute: typeof ShopsShopIdProductsProductIdRoute
  ShopsShopIdProductsNewRoute: typeof ShopsShopIdProductsNewRoute
  ShopsShopIdProductsIndexRoute: typeof ShopsShopIdProductsIndexRoute
}

const ShopsShopIdProductsRouteRouteChildren: ShopsShopIdProductsRouteRouteChildren =
  {
    ShopsShopIdProductsProductIdRoute: ShopsShopIdProductsProductIdRoute,
    ShopsShopIdProductsNewRoute: ShopsShopIdProductsNewRoute,
    ShopsShopIdProductsIndexRoute: ShopsShopIdProductsIndexRoute,
  }

const ShopsShopIdProductsRouteRouteWithChildren =
  ShopsShopIdProductsRouteRoute._addFileChildren(
    ShopsShopIdProductsRouteRouteChildren,
  )

interface ShopsShopIdRouteRouteChildren {
  ShopsShopIdProductsRouteRoute: typeof ShopsShopIdProductsRouteRouteWithChildren
  ShopsShopIdAttributesRoute: typeof ShopsShopIdAttributesRoute
  ShopsShopIdInvitesRoute: typeof ShopsShopIdInvitesRoute
  ShopsShopIdManagersRoute: typeof ShopsShopIdManagersRoute
  ShopsShopIdRolesRoute: typeof ShopsShopIdRolesRoute
  ShopsShopIdVariantsRoute: typeof ShopsShopIdVariantsRoute
  ShopsShopIdIndexRoute: typeof ShopsShopIdIndexRoute
}

const ShopsShopIdRouteRouteChildren: ShopsShopIdRouteRouteChildren = {
  ShopsShopIdProductsRouteRoute: ShopsShopIdProductsRouteRouteWithChildren,
  ShopsShopIdAttributesRoute: ShopsShopIdAttributesRoute,
  ShopsShopIdInvitesRoute: ShopsShopIdInvitesRoute,
  ShopsShopIdManagersRoute: ShopsShopIdManagersRoute,
  ShopsShopIdRolesRoute: ShopsShopIdRolesRoute,
  ShopsShopIdVariantsRoute: ShopsShopIdVariantsRoute,
  ShopsShopIdIndexRoute: ShopsShopIdIndexRoute,
}

const ShopsShopIdRouteRouteWithChildren =
  ShopsShopIdRouteRoute._addFileChildren(ShopsShopIdRouteRouteChildren)

interface ShopsRouteRouteChildren {
  ShopsShopIdRouteRoute: typeof ShopsShopIdRouteRouteWithChildren
  ShopsInvitesRoute: typeof ShopsInvitesRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
}

const ShopsRouteRouteChildren: ShopsRouteRouteChildren = {
  ShopsShopIdRouteRoute: ShopsShopIdRouteRouteWithChildren,
  ShopsInvitesRoute: ShopsInvitesRoute,
  ShopsIndexRoute: ShopsIndexRoute,
}

const ShopsRouteRouteWithChildren = ShopsRouteRoute._addFileChildren(
  ShopsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopsRouteRoute: ShopsRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
